In [1]:
import pandas as pd
import numpy as np
import random
import sklearn.datasets as datasets
from sklearn.datasets import fetch_openml
import sys

sys.path.insert(1, '..')
from check_data_consistency import DataConsistencyChecker

In [2]:
# execute_list = ['DECISION_TREE_CLASSIFIER']

# dc = DataConsistencyChecker()
# synth_df = dc.generate_synth_data(all_cols=False, execute_list=execute_list, add_nones='none')
# dc.init_data(synth_df)

# _ = dc.check_data_quality(execute_list=execute_list)
# dc.display_detailed_results(show_short_list_only=False, show_patterns=True, plot_results=True)

In [3]:
data = fetch_openml('adult', version=1)
df = pd.DataFrame(data.data, columns=data.feature_names)
display(df.head())

dc = DataConsistencyChecker(verbose=0)  
dc.init_data(df)
_ = dc.check_data_quality()

dc.summarize_exceptions_by_test_and_feature()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country
0,2,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States
1,3,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States
2,2,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States
3,3,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States
4,1,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba

Data consistency check complete.
Analysed 48,842 rows, 14 columns
Executed 155 tests.

Patterns without Exceptions:
Found 28 patterns without exceptions
10 tests (6.45% of tests) identified at least one pattern without exceptions each.
By default some patterns are not listed in calls to display_detailed_results().

Patterns with Exceptions:
Found 63 patterns with exceptions
12 tests (7.74% of tests) flagged at least one exception each.
Flagged 2,789 row(s) with at least one exception.
Flagged 13 column(s) with at least one exception.

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country
Test ID,,,,,,,,,,,,,,
RARE_VALUES,,✔,,,,✔,,,,,,,,
MATCHED_MISSING,,✔,,,,,✔,,,,,,,
VERY_SMALL,,,,,✔,,,,,,,,,
VERY_LARGE,,,✔,,,,,,,,,,,
LARGER_THAN_SUM,,,,,✔,,,,,,✔,✔,,
NUMBER_NON-ALPHANUMERIC_CHARS,,,,,,,,,,,,,,✔
RARE_WORDS,,,,✔,,✔,,,,,,,,
LARGE_GIVEN_VALUE,,✔,,,✔,✔,,✔,✔,,,,,
SMALL_GIVEN_PREFIX,,,,,✔,,,✔,,,,,,
LARGE_GIVEN_PAIR,✔,✔,✔,✔,✔,✔,✔,✔,✔,,✔,✔,,✔
SMALL_GIVEN_PAIR,✔,✔,,✔,✔,✔,✔,✔,✔,,,,✔,✔
LARGE_AVG_RANK_PER_ROW,✔,,✔,,✔,,,,,,✔,✔,✔,

In [4]:
def demo_test(filename, test_id_arr, issue_id_arr=None, features_arr=None):
    
    # Load the data
    data = fetch_openml(filename, version=1)
    df = pd.DataFrame(data.data, columns=data.feature_names)
    display(df.head())
    
    # Run DataConsistencyChecker with default parameters, other than verbose=0
    # to skip printing the test IDs as the tests exectute. 
    dc = DataConsistencyChecker(verbose=0)  
    dc.init_data(df)
    _ = dc.check_data_quality(execute_list=test_id_arr)
    
    # If specific issues are specified, list only these.
    if issue_id_arr is not None:
        dc.display_detailed_results(issue_id_list=issue_id_arr)
    elif features_arr is not None:
        dc.display_detailed_results(col_name_list=features_arr)
    else:
        dc.display_detailed_results(test_id_list=test_id_arr)

In [5]:
#demo_test("adult", test_id_arr=['LARGE_GIVEN_PAIR'])